
// 1. Centralized Categories Data
const categories = [
    { id: "all", label: "HOME/ALL" },
    { id: "laptops", label: "LAPTOPS" },
    { id: "used_items", label: "USED ITEMS", color: "red" },
    { id: "new_items", label: "NEW ITEMS", color: "green" },
     { id: "keypad_phones", label: "keypad_phones" },
    { id: "smart_phones", label: "smart_phones" },
    { id: "game_controllers", label: "GAME CONTROLLERS" },
    { id: "chargers", label: "CHARGERS" },
    { id: "men", label: "MEN'S SECTION" },
    { id: "gaming_consoles", label: "GAMING CONSOLES" },
    { id: "ladies", label: "LADIES' SECTION" },
    { id: "kids", label: "KIDS' SECTION" },
    { id: "trusted_taxi", label: "TRUSTED TAXI" },
    { id: "sneekers", label: "SNEEKERS" },
    { id: "hard_drives", label: "hard_drives" },
    { id: "school_items", label: "SCHOOL ITEMS" },
    { id: "workshop_tools", label: "WORKSHOP TOOLS" },
    { id: "jobs", label: "JOBS" },
    { id: "jersey", label: "jersey" },
    { id: "caps", label: "CAPS" },
    { id: "bags", label: "bags" },
    { id: "vehicles", label: "VEHICLES" },
    { id: "jewerly", label: "JEWELRY" },
    { id: "art_craft", label: "ART & CRAFT" },
    { id: "mobile_money_agent", label: "MOBILE MONEY AGENT" },
    { id: "vegetables", label: "VEGETABLES" },
    { id: "batteries", label: "BATTERIES" },
    { id: "power_banks", label: "POWER BANKS" },
    { id: "tvs", label: "TVS" },
    { id: "freezers", label: "FREEZERS" }
];